### ISSUE TITLE
crc32 

### ISSUE THREAD

**Issue by LindaC2031** [janglapuk/pointblank-modtools#1]
On initialization you have:

      for (size_t j = 0; j < 8; j++)
          crc32_table[i] = (crc32_table[i] << 1) ^ (crc32_table[i] & (1 << 31) ? ulPolynomial : 0);

what is the order supposed to be here?
(a&b)?c:d  or a&(b?c:d)  ?

Thank you
Linda

**Comment by janglapuk** [comment]
`
(crc32_table[i] & (1 << 31) ? ulPolynomial : 0)
`

The order supposed to be `a & b ? c : d` because the ternary condition explicitly evaluate (`a & b`) as boolean from AND bitwise operation result.

To make `a & (b ? c : d)`, the code should be like this: `(crc32_table[i] & ((1 << 31) ? ulPolynomial : 0))`
